finbest:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: finbest
      password: finbest_password
      port: 5432
      dbname: finbest
      schema: mart
      threads: 4
